# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/mawang/Documents/业余/python/checkin/diagnosis.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_diagnosis(object):
    def setupUi(self, diagnosis):
        diagnosis.setObjectName("diagnosis")
        diagnosis.setWindowModality(QtCore.Qt.ApplicationModal)
        diagnosis.resize(480, 344)
        self.comboBox = QtWidgets.QComboBox(diagnosis)
        self.comboBox.setGeometry(QtCore.QRect(40, 60, 221, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.textEdit = QtWidgets.QTextEdit(diagnosis)
        self.textEdit.setGeometry(QtCore.QRect(40, 140, 401, 91))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(diagnosis)
        self.pushButton.setGeometry(QtCore.QRect(340, 60, 80, 26))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(diagnosis)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 270, 80, 26))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(diagnosis)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 270, 80, 26))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(diagnosis)
        self.pushButton_3.clicked.connect(diagnosis.close)
        QtCore.QMetaObject.connectSlotsByName(diagnosis)

    def retranslateUi(self, diagnosis):
        _translate = QtCore.QCoreApplication.translate
        diagnosis.setWindowTitle(_translate("diagnosis", "诊断编辑器"))
        self.comboBox.setItemText(1, _translate("diagnosis", "ARDS"))
        self.comboBox.setItemText(2, _translate("diagnosis", "肾功能衰竭"))
        self.comboBox.setItemText(3, _translate("diagnosis", "肝功能衰竭"))
        self.comboBox.setItemText(4, _translate("diagnosis", "心力衰竭"))
        self.comboBox.setItemText(5, _translate("diagnosis", "呼吸衰竭"))
        self.comboBox.setItemText(6, _translate("diagnosis", "循环衰竭"))
        self.comboBox.setItemText(7, _translate("diagnosis", "胰腺炎"))
        self.comboBox.setItemText(8, _translate("diagnosis", "肺炎"))
        self.pushButton.setText(_translate("diagnosis", "加入"))
        self.pushButton_2.setText(_translate("diagnosis", "写入"))
        self.pushButton_3.setText(_translate("diagnosis", "离开"))
